### ISSUE TITLE
Jenkinsのリポジトリミラーがほしい

### ISSUE THREAD

**Issue by cradle8810** [cradle8810/ansible_hayaworld#303]
毎回JenkinsでActionsがコケるので

**Comment by cradle8810** [comment]
https://ftp.yz.yamagata-u.ac.jp/pub/misc/jenkins/debian/
が一番近いミラー。

geerlingguy氏のとおり下記のように変数を指定すればよさそう

```yaml
# For Debian/Ubuntu:
jenkins_repo_url: deb https://pkg.jenkins.io/debian{{ '-stable' if (jenkins_prefer_lts | bool) else '' }} binary/
jenkins_repo_key_url: https://pkg.jenkins.io/debian{{ '-stable' if (jenkins_prefer_lts | bool) else '' }}/jenkins.io.key
```
